dapphub/dapptools

- .travis.yml
This allows us to build the whole suite on each commit, and upload the
paths to cachix.
> CI: Add .travis.yml

- src/dapp/libexec/dapp/dapp---parse-deps
- src/dapp/libexec/dapp/dapp-install
- src/dapp/libexec/dapp/dapp-pkg
> Document 3 dapp subcommands

- Makefile
- README.md
* Removes usage of `make`
* Fix `nix-env` invocation
> Update install instructions

- src/hevm/src/EVM.hs
- src/hevm/src/EVM/Format.hs
- src/hevm/src/EVM/TTY.hs
Populate the returndata buffer on revert. Fixes #8
> Fully implement REVERT

- src/dapp/README.md
> dapp: mention Bash 4 requirement for macOS

- src/seth/README.md
Added some nuances about key management that I didn't realize to the README in case it might be helpful to others developing with seth!
> key management details

- src/dapp/README.md
> Add environment variables to README

- src/hevm/src/EVM/Format.hs
> hevm/src/EVM/Format.hs: try to decode and display revert error string

- .travis.yml
> travis: pin cachix at v0.1.3

- nix/solc-versions.nix
- overlay.nix
- src/dapp/CHANGELOG.md
- src/dapp/default.nix
- src/dapp/libexec/dapp/dapp---version
> solc 0.5.6

- src/dapp-tests/constantinople.sol
- src/hevm/CHANGELOG.md
- src/hevm/Makefile
- src/hevm/default.nix
- src/hevm/hevm-cli/hevm-cli.hs
- src/hevm/hevm.cabal
- src/hevm/run-blockchain-tests
- src/hevm/src/EVM.hs
- src/hevm/src/EVM/Concrete.hs
- src/hevm/src/EVM/Debug.hs
- src/hevm/src/EVM/Exec.hs
- src/hevm/src/EVM/Facts.hs
- src/hevm/src/EVM/FeeSchedule.hs
- src/hevm/src/EVM/Fetch.hs
- src/hevm/src/EVM/Format.hs
- src/hevm/src/EVM/Keccak.hs
- src/hevm/src/EVM/TTY.hs
- src/hevm/src/EVM/Transaction.hs
- src/hevm/src/EVM/Types.hs
- src/hevm/src/EVM/UnitTest.hs
- src/hevm/src/EVM/VMTest.hs
- src/hevm/test/test.hs
(please don't merge yet, this is still WIP)
Aim is to resolve #92.
> run BlockchainTests/GeneralStateTests

- src/seth/libexec/seth/seth---to-int256
addresses https://github.com/dapphub/dapptools/issues/170
> add seth---to-int256 macro

- src/ethsign/ethsign.go
Just a minor clean up. Addresses (part of) https://github.com/dapphub/dapptools/issues/121
> ethsign: factor out repetitions

- src/seth/CHANGELOG.md
- src/seth/default.nix
- src/seth/libexec/seth/seth---version
> seth: 0.8.2

- src/hevm/hevm.el
- src/hevm/src/EVM/Emacs.hs
It works, but it gets a bit slow as soon as emacs saves some huge bytecodes into its cache. :cry:
> bytecode view in hevm.el

- haskell.nix
- nix/libff.nix
- nix/libff.patch
- src/hevm/default.nix
- src/hevm/ethjet/ethjet-ff.cc
- src/hevm/ethjet/ethjet-ff.h
- src/hevm/ethjet/ethjet.c
- src/hevm/ethjet/ethjet.h
- src/hevm/hevm-cli/hevm-cli.hs
- src/hevm/hevm.cabal
- src/hevm/shell.nix
- src/hevm/src/EVM.hs
- src/hevm/src/EVM/FeeSchedule.hs
- src/hevm/src/EVM/Types.hs
- src/hevm/src/EVM/VMTest.hs
- src/hevm/test/test.hs
and also fixes some precompile-related bugs, refactors precompile handling.
**GeneralStateTests status**: 6015 passed, 3782 bad-balance, 815 failed.
Thanks @cmditch 😊.  This is now ready to merge IMO.
> hevm: add SHA256, RIPEMD, IDENTITY, MODEXP, ECADD, ECMUL, ECPAIRING precompiles

- README.md
- nix/solc-updates.md
- nix/solc-versions.nix
- src/dapp/CHANGELOG.md
- src/dapp/default.nix
- src/dapp/libexec/dapp/dapp---version
Also added instructions for updating solc versions
> Add support for solc-0.5.8

- src/dapp/CHANGELOG.md
- src/dapp/default.nix
- src/dapp/libexec/dapp/dapp---version
This bumps the version after merging #231.
> dapp: 0.22.0

- nix/solc-versions.nix
- overlay.nix
- src/dapp/CHANGELOG.md
- src/dapp/default.nix
Adds it and makes it the default.
Releases dapp 0.24.0.
Closes #242.
> Solc 0.5.10

- nix/ethabi.nix
- overlay.nix
- src/hevm/CHANGELOG.md
- src/hevm/hevm-cli/hevm-cli.hs
- src/hevm/src/EVM.hs
- src/hevm/src/EVM/TTY.hs
- src/hevm/src/EVM/Types.hs
Some minor improvements to exec.
> hevm: improve exec

- src/hevm/CHANGELOG.md
- src/hevm/README.md
- src/hevm/src/EVM/TTY.hs
added key-bindings help (h)
added memory pager view (M)
moved event handlers to a function
> hevm: tty memory pager - fixes #164

- src/dapp/libexec/dapp/dapp---testnet-launch
> dapp: correctly load testnet with multiple accounts

- src/hevm/src/EVM/UnitTest.hs
Fixes https://github.com/dapphub/dapptools/issues/302
> Fixes #302

- nix/solc-versions.nix
> solc: get 0.5.15 from upstream

- src/dapp/libexec/dapp/dapp-verify-contract
- src/seth/README.md
- src/seth/libexec/seth/seth
Updates to allow etherscan verification on goerli
> Update for goerli verification

- src/seth/libexec/seth/seth-calldata
Adds support for array arguments in `seth calldata`.
> seth-calldata: multiple args support

- src/seth/README.md
I tried out --to-bytes32 on a few things and it seems to only work with numbers. Is that right?
> Updated readme to include --to- address int256 uint256 and bytes32

- src/seth/libexec/seth/seth---version
We had missed this while releasing seth in the previous commits.
> seth: 0.8.2 -> 0.8.4

- src/hevm/hevm-cli/hevm-cli.hs
adds the `replay` option to `hevm interactive` so that it doesn't always fail
> Interactivefix

- src/dapp/default.nix
- src/seth/default.nix
- src/token/default.nix
Cleanups that have no effect on semantics.
> Optional string

- src/dapp/libexec/dapp/dapp---testnet-launch
The upgrade from Geth 1.8 to 1.9 required a couple of changes...
> Fix dapp testnet command

- src/seth/libexec/seth/seth-estimate
> - added support for decimal block number to seth estimate;

- src/dapp/libexec/dapp/dapp-combined-json
- src/hevm/hevm-cli/hevm-cli.hs
- src/hevm/src/EVM/Facts.hs
- src/hevm/src/EVM/TTY.hs
- src/seth/CHANGELOG.md
- src/seth/Makefile
- src/seth/default.nix
- src/seth/libexec/seth/seth
- src/seth/libexec/seth/seth---nix-run
- src/seth/libexec/seth/seth---use
- src/seth/libexec/seth/seth-block
- src/seth/libexec/seth/seth-bundle-source
- src/seth/libexec/seth/seth-combined-json
- src/seth/libexec/seth/seth-debug
- src/seth/libexec/seth/seth-get-full-block-by-hash
- src/seth/libexec/seth/seth-get-full-block-by-number
- src/seth/libexec/seth/seth-run-tx
- src/seth/libexec/seth/seth-source
Adds the ability to run live transactions through hevms interactive debugger.
if you have an  ETH_RPC_URL with archive state, you can probably try this example
```
seth debug 0x3b844d781f40eb2bb3c4bc168c852b3766446777d2299e9b8b83df3d6fdbb176
```
otherwise, pick your favorite recent transaction to debug.
> seth debug and seth run-tx

- src/hevm/CHANGELOG.md
- src/hevm/hevm-cli/hevm-cli.hs
- src/hevm/src/EVM.hs
- src/hevm/src/EVM/Dev.hs
- src/hevm/src/EVM/VMTest.hs
woops #415 had wrong target, should be aimed for master
> Simplifyexec

- src/dapp/CHANGELOG.md
> src/dapp/CHANGELOG.md: update Unreleased

- src/hevm/src/EVM/UnitTest.hs
> Fix UnitTest vm errors

- .github/workflows/release.yml
> .github/workflows/release.yml: match multi major

- src/hevm/src/EVM.hs
Another simplifcation factored out of #353
> refactor calling checks

- overlay.nix
> remove dappsys

- src/dapp/CHANGELOG.md
- src/dapp/libexec/dapp/dapp---make-library-state
- src/dapp/libexec/dapp/dapp-build
Addresses #426, @realisation please try it out
> dapp: fix dapp test for use with libraries

- src/seth/CHANGELOG.md
- src/seth/libexec/seth/seth---from-ascii
- src/seth/libexec/seth/seth---from-wei
- src/seth/libexec/seth/seth---max-int
- src/seth/libexec/seth/seth---max-uint
- src/seth/libexec/seth/seth---min-int
- src/seth/libexec/seth/seth---to-address
- src/seth/libexec/seth/seth---to-ascii
- src/seth/libexec/seth/seth---to-dec
- src/seth/libexec/seth/seth---to-fix
- src/seth/libexec/seth/seth---to-hex
- src/seth/libexec/seth/seth---to-hexdata
- src/seth/libexec/seth/seth---to-int256
- src/seth/libexec/seth/seth---to-uint256
- src/seth/libexec/seth/seth---to-wei
- src/seth/libexec/seth/seth-keccak
Read stdin from conversion functions and add `--{max,min}-(u)int` helpers.
> seth usability tweaks

- nix/solc-versions.nix
> solc: don't build 4.18 on osx

- src/hevm/hevm-cli/hevm-cli.hs
- src/hevm/src/EVM.hs
- src/hevm/src/EVM/Exec.hs
- src/hevm/src/EVM/UnitTest.hs
- src/hevm/src/EVM/VMTest.hs
- src/seth/CHANGELOG.md
- src/seth/README.md
- src/seth/libexec/seth/seth
- src/seth/libexec/seth/seth-accounts
- src/seth/libexec/seth/seth-call
- src/seth/libexec/seth/seth-combined-json
- src/seth/libexec/seth/seth-debug
- src/seth/libexec/seth/seth-mktx
- src/seth/libexec/seth/seth-rpc-curl
- src/seth/libexec/seth/seth-run-tx
- src/seth/libexec/seth/seth-send
Adds two new flags:
- `seth call --hevm`: execute a call with hevm
- `seth call --debug`: execute a call interactively with hevm.
No squash merge please.
> seth call --debug

- src/hevm/hevm-cli/hevm-cli.hs
unlimited by default is probabily a little user unfriendly
> hevm: default smttimeout to 20s

- src/hevm/CHANGELOG.md
- src/hevm/src/EVM/ABI.hs
- src/hevm/src/EVM/Types.hs
> better shrinking and generator choices for abivalues

- src/hevm/README.md
see:  https://github.com/dapphub/dapptools/pull/465#discussion_r463944958
> hevm: readme: correct max length for fully abstract calldata

- nix/hevm-tests/smt-checker.nix
Had some CI failures due to timeouts on macOS overnight....
> nix: hevm-tests: smtChecker: bump timeout to 90s

- haskell.nix
- src/hevm/CHANGELOG.md
- src/hevm/hevm-cli/hevm-cli.hs
- src/hevm/hevm.cabal
- src/hevm/src/EVM.hs
- src/hevm/src/EVM/Exec.hs
- src/hevm/src/EVM/Fetch.hs
- src/hevm/src/EVM/SymExec.hs
- src/hevm/src/EVM/UnitTest.hs
- src/hevm/src/EVM/VMTest.hs
- src/hevm/test/test.hs
Implements the ability to have symbolic storage for multiple contracts by creating fresharrays in Fetch.hs and using the new `sArrayList` technology from sbv
> Globalstorage

- src/hevm/src/EVM/Symbolic.hs
> add forceBuffer

- src/hevm/src/EVM.hs
- src/hevm/src/EVM/Format.hs
- src/hevm/src/EVM/TTY.hs
> clearer unknown contract call formatting

- src/dapp/CHANGELOG.md
- src/dapp/libexec/dapp/dapp---hevm-opts
- src/dapp/libexec/dapp/dapp---make-cache
- src/dapp/libexec/dapp/dapp---make-library-state
- src/hevm/CHANGELOG.md
- src/hevm/hevm-cli/hevm-cli.hs
- src/hevm/src/EVM.hs
- src/hevm/src/EVM/Dev.hs
- src/hevm/src/EVM/Facts.hs
- src/hevm/src/EVM/UnitTest.hs
rpc cache for dapp
```
dapp --make-cache /tmp/dapp.cache 
dapp test --rpc --cache /tmp/dapp.cache
```
> hevm: rpc cache

- src/seth/libexec/seth/seth-source
I introduced a typo. Also this sets the appropriate defaults for other chains
> fix seth source

- src/hevm/hevm-cli/hevm-cli.hs
- src/hevm/src/EVM/ABI.hs
- src/hevm/src/EVM/Solidity.hs
- src/hevm/src/EVM/TTY.hs
- src/hevm/src/EVM/UnitTest.hs
Trivial changes, merging immediately after CI success
> small changes for easier act integration

- src/hevm/CHANGELOG.md
- src/hevm/README.md
- src/hevm/src/EVM/TTY.hs
Implements `P` and `C-p` commands which takes larger steps back, analogously to how `N` and `C-n` step forward
> Bigbackstep

- src/hevm/CHANGELOG.md
- src/hevm/hevm-cli/hevm-cli.hs
- src/hevm/src/EVM.hs
- src/hevm/src/EVM/Concrete.hs
- src/hevm/src/EVM/Fetch.hs
- src/hevm/src/EVM/Format.hs
- src/hevm/src/EVM/Stepper.hs
- src/hevm/src/EVM/SymExec.hs
- src/hevm/src/EVM/Symbolic.hs
- src/hevm/src/EVM/TTY.hs
- src/hevm/src/EVM/Types.hs
- src/hevm/src/EVM/VMTest.hs
- src/hevm/test/test.hs
> Tree view and semantic information with `Whiff` views

- src/hevm/src/EVM.hs
- src/hevm/src/EVM/TTY.hs
- src/hevm/src/EVM/UnitTest.hs
- src/hevm/test/test.hs
This is just syntactic changes except for the bugfix in UnitTest.setupCall
> simplify TTY state, minor clean ups

- src/hevm/hevm-cli/hevm-cli.hs
- src/hevm/src/EVM/Dapp.hs
- src/hevm/src/EVM/Dev.hs
> skip zero matching contracts

- src/dapp/libexec/dapp/dapp---version
> bump to actual version

- src/hevm/src/EVM/TTY.hs
> fix debug replay

- src/dapp/libexec/dapp/dapp---use
- src/seth/libexec/seth/seth---use
> query nix store for solc

- src/dapp/libexec/dapp/dapp---use
- src/seth/libexec/seth/seth---use
> Fix typo in (dapp|seth) --use

- src/hevm/src/EVM/TTY.hs
The simplifications involved in #552  messed up the ability to select branches while debugging symbolic executions. Here's a simple fix
> fix branching bug

- src/dapp/CHANGELOG.md
- src/dapp/default.nix
- src/dapp/libexec/dapp/dapp---version
- src/hevm/CHANGELOG.md
- src/hevm/hevm.cabal
- src/seth/CHANGELOG.md
- src/seth/default.nix
- src/seth/libexec/seth/seth---version
> Release: hevm/0.43.1 seth/0.9.4 dapp/0.31.1

- src/hevm/src/EVM/ABI.hs
> fix abi parsing

- src/hevm/src/EVM/Flatten.hs
Makes `hevm flatten` work with `--standard-json` as well as `--combined-json`
> flatten standard-json

- src/dapp/libexec/dapp/dapp-init
> fix dapp init

- src/dapp-tests/integration/tests.sh
- src/dapp/libexec/dapp/dapp-build
see https://github.com/dapphub/dapptools/issues/610
> dapp: fix dapp-build with custom standard-json

- src/dapp/README.md
- src/dapp/libexec/dapp/dapp-mk-standard-json
Allows setting the number of runs via env vars.
> Added support for DAPP_BUILD_OPTIMIZE_RUNS

- src/seth/README.md
added brief description of array usage in seth with an example
> added array usage to README

- src/ethsign/CHANGELOG
- src/ethsign/README.md
- src/ethsign/default.nix
- src/ethsign/ethsign.go
- src/seth/CHANGELOG.md
Not a go expert but this seems to work. Ping @livnev
> Ethsignledgerlive

- src/seth/libexec/seth/seth
- src/seth/libexec/seth/seth-chain
- src/seth/libexec/seth/seth-etherscan-source
This is a small update for seth to support binance smart chain
> add binance smart chain to seth

- src/dapp-tests/default.nix
- src/dapp-tests/fail/invariantFail.sol
- src/dapp-tests/pass/invariants.sol
- src/dapp/CHANGELOG.md
- src/dapp/README.md
- src/hevm/CHANGELOG.md
- src/hevm/hevm-cli/hevm-cli.hs
- src/hevm/src/EVM.hs
- src/hevm/src/EVM/Dapp.hs
- src/hevm/src/EVM/Dev.hs
- src/hevm/src/EVM/Format.hs
- src/hevm/src/EVM/Solidity.hs
- src/hevm/src/EVM/Stepper.hs
- src/hevm/src/EVM/SymExec.hs
- src/hevm/src/EVM/TTY.hs
- src/hevm/src/EVM/UnitTest.hs
Concept art for #644. Seems to work pretty well except it doesn't have any replay functionality yet
EDIT; now implemented
> ds-test invariants; testing functions run against arbitrary contract state

- src/dapp-tests/default.nix
- src/hevm/hevm-cli/hevm-cli.hs
We're still hitting this unfortunate sbv issue :(
https://github.com/dapphub/dapptools/issues/671
> hevm: default to z3 for smt solving

- src/dapp/libexec/dapp/dapp
Fixes https://github.com/dapphub/dapptools/issues/674
Context: https://github.com/dapphub/dapptools/issues/674#issuecomment-870982337
> dapp: Load .dapprc before setting DAPP_REMAPPINGS

- .github/scripts/install-solc.sh
> ci: use solc 0.8.6 in macos release pipeline

- .github/scripts/install-solc.sh
- .github/workflows/release.yml
Lets try this again..... :upside_down_face:
> Release Redux

- haskell.nix
- nix/libff.nix
- overlay.nix
act would just instantly segfault when built against static hevm, with this it works :)
> nix: add shared haskell package set

- src/seth/README.md
Add additional documentation on seth commands and ensure they are all sorted alphabetically
> Add commands to seth docs

- src/seth/libexec/seth/seth---use
same as https://github.com/dapphub/dapptools/pull/720 but for seth as well
> seth: fix seth --use

- src/hevm/src/EVM/ABI.hs
- src/hevm/src/EVM/Dapp.hs
- src/hevm/src/EVM/Format.hs
- src/hevm/src/EVM/Solidity.hs
Fixes issue #669.
In action:
Many thanks to @TransmissionsDev for setting me up with a test repo so I wasn't doing this completely blind!
Refinements welcome, etc etc - here to help!
> Support sol 0.8.4 custom error type

- src/dapp/README.md
- src/dapp/libexec/dapp/dapp
- src/dapp/libexec/dapp/dapp---hevm-opts
- src/dapp/libexec/dapp/dapp-test
- src/hevm/README.md
- src/hevm/hevm-cli/hevm-cli.hs
- src/hevm/src/EVM/UnitTest.hs
My first attempt at some substantive haskell contributions. thanks @d-xo for all the guidance 🙏 ❤️
> hevm: --cov-match flag

- src/hevm/hevm-cli/hevm-cli.hs
> hevm: symbolic: show tree if postcondition query times out

- src/hevm/hevm.cabal
- src/hevm/src/EVM/Facts.hs
- src/hevm/src/EVM/Fetch.hs
This reverts commit f9f5b509ffa40381764313bf5f892068a53174d7.
May solve #747
> Revert "fetch contract code, nonce and balance asynchronously"

- src/dapp-tests/integration/tests.sh
- src/ethsign/default.nix
- src/ethsign/ethsign.go
- src/ethsign/go.mod
- src/seth/CHANGELOG.md
- src/seth/README.md
- src/seth/libexec/seth/seth
- src/seth/libexec/seth/seth---send-params
- src/seth/libexec/seth/seth-mktx
No algorithms for setting prio fee, just a good old manual flags allowing for eip1559 txs. 
Haven't tried this out much yet, brave guinea pigs appreciated
> dynamic fee txs (EIP-1559 support)

- .github/pull_request_template.md
Hopefully automates my changelog related review comments a little :grinning:
> github: add pr template

- src/seth/README.md
- src/seth/libexec/seth/seth-lookup-address
Fix docs for `seth lookup-address`
> seth (docs): fix lookup-address docs

- src/dapp/README.md
context: https://github.com/dapphub/dapptools/issues/753
> Add example to dapp verify-contract

- src/hevm/src/EVM/ABI.hs
- src/hevm/src/EVM/Format.hs
- src/hevm/src/EVM/Solidity.hs
Not tested, but should address https://github.com/crytic/echidna/pull/674#issuecomment-941006379. Is this what you are looking for @ggrieco-tob ?
> add event parameter name

- .github/workflows/build.yml
- src/hevm/src/EVM/ABI.hs
- src/hevm/src/EVM/Format.hs
- src/hevm/src/EVM/Solidity.hs
> Cachixbump

- README.md
Just a tiny comment to make life easier for m1 users and avoid some research.
> More context for m1 users

- src/dapp/libexec/dapp/dapp-verify-contract
- src/seth/libexec/seth/seth-chain
- src/seth/libexec/seth/seth-etherscan-source
This pull request extends the following MR #853 
Example of verified contract on polygon mumbai using dapptools  https://mumbai.polygonscan.com/address/0xae3177d9246b5c657d9FAc5f05D364D854834Bbf#code
> Add Polygon Mumbai support

- src/dapp/libexec/dapp/dapp-verify-contract
Example verified contract on Optimism Kovan using dapptools: https://kovan-optimistic.etherscan.io/address/0xCfa416EfaB7D4638a991A4F8fee7E98CeF4a06E0#code
> Add Optimism Kovan verification support

- nix/solc-static-versions.nix
- src/hevm/CHANGELOG.md
> solc static version for 0.8.11

- src/hevm/hevm-cli/hevm-cli.hs
> fix: Blockhain -> Blockchain in hevm-cli.hs

- src/dapp/libexec/dapp/dapp-verify-contract
- src/seth/libexec/seth/seth-chain
- src/seth/libexec/seth/seth-etherscan-source
> adding fantom support!

- src/dapp/libexec/dapp/dapp-verify-contract
- src/seth/libexec/seth/seth-chain
- src/seth/libexec/seth/seth-etherscan-source
* Add support for verifying smart contracts on arbitrum one and arbitrum rinkeby
* Add support for arbitrum rinkeby in `seth chain`
* Add support for arbitrum rinkeby in `seth etherscan-source`
* Fix support for arbitrum one in `seth etherscan-source`
> Arbitrum fixes and improvements

- src/dapp/libexec/dapp/dapp-verify-contract
- src/seth/libexec/seth/seth-chain
Add contract verification support on Avalanche network.
> Avalanche contract verification support

- src/dapp/libexec/dapp/dapp-verify-contract
> Add Optimism Mainnet Verification support

- overlay.nix
it can't be used in flake if not pure.
> Make overlay evaluation pure

- src/hevm/README.md
Added missing package to hevm install.
> updated install for mac instructions

- nix/solidity-package.nix
- nix/solidity-package.sh
Should fix #921 
Can you confirm @gbalabasquer ?
> nix: rm leftover dapp2 refs

- src/seth/README.md
Took me one hour to figure out how to do it, and no example found in all makerdao repos.
> add string arguments instructions

- ARCHITECTURE.md
> expand architecture docs

- src/hevm/src/EVM/SymExec.hs
More rewrite rules about SHL and SHR -- much easier to read output :)
> More rewrite rules

- src/hevm/src/EVM/Types.hs
> Fixing a bit of PLEq/PGEq/etc.

- src/seth/README.md
Just a very minor syntax fix :-)
- [x ] updated the docs
> 📚 Fix typo in README example

- .github/workflows/build.yml
- .github/workflows/release.yml
Fixes this issue: https://discourse.nixos.org/t/nix-2-14-0-released/25900/4
> ci: upgrade nix-install-action

- flake.nix
Exposes our solc versions in the nix flake
> flake: expose solc static versions
