- .travis.yml
Every successful Travis build will be announced on the `#announce` channel on dapphub.chat.
Currently, all commits to all branches produce an announce message.
The messages looks like 
> Linux and Darwin packages for commit `8114cf4a` on branch `asymmetric/ci-bot` built and uploaded to `dapp.cachix.org`
**NOTE**: Two new env variables introduced:
* `CHAT_AUTH_TOKEN`
* `CHAT_USER_ID`
These must be set as project variables on Travis.
> Announce new commits on dapphub chat

- src/hevm/src/EVM.hs
While capturing the returndata, it was the length from the `CALL` opcode, but not the length from the `RETURN` that was being used as the returndata length. It means that if a `CALL` was made with `outsize=0`, no returndata got saved so even subsequent `RETURNDATASIZE` and `RETURNDATACOPY` opcodes could not retrieve it.
> `RETURN` opcode handling fixed (in case of variable length return data)

- src/hevm/README.md
- src/seth/README.md
Instead, tell people to install as part of Dapp tools.
> Remove channel-based install instructions

- .travis.yml
`#dev` was becoming noisy with all the notices of new builds. `#dev-announce` is a read-only channel, where only the `ci-bot` user has write permissions.
> Post build notices in #dev-announce

- src/hevm/CHANGELOG.md
- src/hevm/default.nix
- src/hevm/hevm.cabal
- src/hevm/src/EVM.hs
Experimental feature. This allows for setting the block timestamp from
within ds-test.
This feature should be used carefully as it is hevm specific and
prevents your ds-tests from running on arbitrary EVM implementations.
Usage:
```
hevm = Hevm(0x7109709ECfa91a80626fF3989D68f67F5b1DD12D);
hevm.warp(42);
```
where
```
contract Hevm {
function warp(uint256) public;
}
```
> (re)enable cheat address

- src/dapp/CHANGELOG.md
Adds an empty changelog, as it doesn't make sense to list any features, since this is the first release with a changelog, and we'd have to list them all under "Added".
> dapp: add changelog

- src/hevm/README.md
Mac OS users have to deal with `readline` and `secp256k1` installations before being able to install hevm with Stack. This PR clarifies it on the README.
Also it updates the directories for the stack and cabal installations (they were referencing the old repository) and speaks about the possibility of installing hevm via Hackage.
> Added Mac OS hevm installation subtleties

- src/dapp/default.nix
- src/dapp/libexec/dapp/dapp---version
- src/dapp/libexec/dapp/dapp-test-hevm
- src/hevm/CHANGELOG.md
- src/hevm/default.nix
- src/hevm/hevm.cabal
- src/hevm/src/EVM/Format.hs
- src/hevm/src/EVM/UnitTest.hs
With this change:
- `dapp test`: shows traces for failing tests
- `dapp test --verbose`: also show traces for passing tests
Also, emit raw event data in the case of anonymous events (e.g. ds-note).
@gbalabasquer @nanexcool :)
> enable hevm traces on passing unit tests

- src/ethsign/ethsign.go
This request enables to use the feature `ethsign tx --signature-only ...` to only return the signature , and not the whole raw tx data. This enables us to use ethsign with Metamasks new external signing feature.
> --signature-only feature added for tx to return signature only

- release.nix
`nix-build` does not evaluate sets recursively. This allows us to build all `solc` versions every time there's a change.
> nix: remove recursion from stable set

- src/seth/CHANGELOG.md
- src/seth/libexec/seth/seth---version
- src/seth/libexec/seth/seth-abi
This way, we don't have to update it manually whenever there are new,
backwards-incompatible solc releases.
See #82 and the fix in eee3859cc155e6e89e99bc16139ad72adbc3e5fc.
> seth: pass current solidity version to seth-abi

- overlay.nix
> nix: use recursive attribute set

- src/hevm/hevm.el
- src/hevm/src/EVM/Emacs.hs
Currently, on steps with no srcmap, `hevm emacs` omits not only the srcmap-related data but also all VM data except for the `pc`, for some reason. I changed it to only omit the data that is actually missing, so that on steps where there is no source, `hevm.el` can update the stack, clear the source overlay, and display `No srcmap!` in the minibuffer. This behaviour is more or less consistent with what `hevm interactive` does when the srcmap is missing.
Perhaps this fails on some edge cases but I wasn't able to find them...
(fixes #113 )
> Emacs srcmap fix

- nix/ethabi/LICENSE
ethabi's code [mentions](https://github.com/dapphub/dapptools/blob/master/nix/ethabi/ethabi/Cargo.toml#L6) the MIT license.
> ethabi: add LICENSE

- nix/solc/post-0.5.2.nix
It's an [optional flag](https://solidity.readthedocs.io/en/latest/installing-solidity.html#smt-solvers), and we don't need it in the dss deployment scripts.
> solc: make z3 support optional, but defaulted true

- default.nix
Go 1.9 has been deprecated ([0][], [1][]) for security reasons, making the overlay difficult to use with more recent versions of nixpkgs.
[0]: https://github.com/NixOS/nixpkgs/commit/a687ef973990cbde6dd350a8db54deb86a4c5d83#diff-501e4080c647067030adbce370423f53
[1]:
https://github.com/NixOS/nixpkgs/commit/d32e779ae850a7053218ebc6d99d34a3f2e6eed3#diff-501e4080c647067030adbce370423f53
> Bump NixOS version

- src/dapp/CHANGELOG.md
- src/dapp/default.nix
it's used by dapp-init.
Closes #111.
> dapp: add gnumake as a dependency

- overlay.nix
Before this patch, unreleased versions were under
`solc-versions.unreleased`.
dapp-use though expects all solc versions to be under the `solc-versions`
attribute.
> nix: fix dapp-use for unreleased solc versions

- nix/solc-versions.nix
- overlay.nix
- src/dapp/CHANGELOG.md
Fix regression in which the default solc was set to 0.5.3, rather than 0.5.4
> dapp: make solc 0.5.4 the default

- src/ethsign/CHANGELOG
- src/ethsign/default.nix
- src/ethsign/ethsign.go
Adds a flag to sign message without the sacred prefix `\x19Ethereum Signed Message:\n`
Read https://github.com/ethereum/go-ethereum/pull/2940 or https://github.com/ethereum/EIPs/blob/master/EIPS/eip-712.md for additional context
> ethsign: add no-prefix flag

- src/dapp/CHANGELOG.md
- src/dapp/libexec/dapp/dapp-create
Reverts the change that added a label to the output of `dapp create`, because it makes it harder for it to be composed.
> dapp: 0.18.1

- src/seth/libexec/seth/seth-call
- src/seth/libexec/seth/seth-estimate
- src/seth/libexec/seth/seth-send
The output of `seth---send-params` is a space-separated list of words on
one line, rather than on multiple lines, so mapfile followed by `$params[@]` was
outputting a quoted string, which broke json parsing.
Closes #180.
/cc @nanexcool @icetan @kmbarry1
> seth: fix SC2207 by using the read builtin

- src/dapp/libexec/dapp/dapp-test-hevm
- src/hevm/CHANGELOG.md
- src/hevm/default.nix
- src/hevm/hevm-cli/hevm-cli.hs
- src/hevm/hevm.cabal
- src/hevm/src/EVM/Dev.hs
- src/hevm/src/EVM/Emacs.hs
- src/hevm/src/EVM/Format.hs
- src/hevm/src/EVM/TTY.hs
- src/hevm/src/EVM/UnitTest.hs
Modifies the `dapp test` output, hiding the trace by default and allowing showing the trace for passing tests.
- `dapp test`: only assertion failures for failing tests
- `dapp test -v`: full trace for failing tests
- `dapp test -vv`: full trace for all tests
Also, display unknown event output in `logn` binary form, including topics.
Fixes #159
> More control over hevm test output

- src/dapp/libexec/dapp/dapp-install
Also fleshed out the usage blurb a bit to cover the three syntaxes.
> no-arg 'dapp install' prints usage

- nix/solidity-package.nix
To allow for inversion of control of which version of `solc` to compile with.
This is useful when you need to provide a version of `solc` other then the current default one so that you can comply with the pragma of the contracts you want to compile.
> Add `solc` argument to `solidityPackage`

- nix/solidity-package.sh
To fix `Source “<filename>” not found: File outside of allowed directories.` problem when using `solidityPackage` with `deps`.
> Add `solc --allow-paths` flag for nix store paths in `solidityPackage` builder

- nix/solidity-package.nix
- nix/solidity-package.sh
To be able to build `solidityPackage`s with specific requirements on HEVM version to run tests.
> Injection of `test-hevm`

- .travis.yml
Avoids trying to push on external PR builds.
Also changes from a second invocation of `cachix push` to a `sleep 10`, mostly because it works with a pipe and a conditional.
The real fix would be if the daemon would [accept signals](https://github.com/cachix/cachix/issues/53).
> travis: only push when building upstream

- src/dapp/libexec/dapp/dapp-init
@nanexcool made this one really easy with a previous commit referenced in the issue. :-)  I moved his [code](https://github.com/dapphub/dapp/pull/80/files) over to this repo.  When I manually ran `dapp-init` in this repo, `.gitattributes` is created and checked in with other init files.
Closes Issue #33
> add create gitattributes to dapp-init

- src/seth/libexec/seth/seth-call
- src/seth/libexec/seth/seth-estimate
- src/seth/libexec/seth/seth-send
This caused subtle errors when using `ETH_RPC_ACCOUNTS=yes` together with
`seth send`.
> Revert changes to how `seth --send-params` are passed to `jshon`

- nix/solidity-package.nix
- nix/solidity-package.sh
To be able to set e.g. `--optimize` flag when using `solidityPackage` Nix expression to build solidity contracts.
This is equivalent to setting `SOLC_FLAGS` for `dapp build`.
> Add `solcFlags` argument to `solidityPackage` that passes flags to `solc`

- src/hevm/src/EVM/TTY.hs
By popular demand: also made is so that advancing past the end of execution just blocks instead of halting `hevm`. To exit `hevm` you have to press `Esc`.
> hevm: add "e" for stepping to end in interactive

- src/hevm/src/EVM/Format.hs
fixes #198 
```
"Error: Wrong `uint' value"
Expected: 1250000000000000000
Actual: 1250000000000000001
"Error: Wrong `int' value"
Expected: -1250000000000000000
Actual: -1250000000000000001
"Error: Wrong `uint' value"
Expected: 1250000000000000000
Actual: 1
```
Could consider right justifying.
> hevm: regular integer notation in test output

- src/hevm/Makefile
- src/hevm/shell.nix
use `cabal new-*` cmds (https://www.haskell.org/cabal/users-guide/nix-local-build-overview.html)
as well as `--pure` with `nix-shell` invocations (https://nixos.org/nix/manual/#options-1)
Note - Credit to @livnev for the proposed changes. Just snagged an opportunity to make this change/PR for ceremonial purposes.
> Update HEVM Makefile

- src/hevm/default.nix
- src/hevm/hevm-cli/hevm-cli.hs
- src/hevm/hevm.cabal
```
$ hevm version
0.30
```
Not sure if `--version` is preferable, or even how to get optparse-generic to do that.
> hevm: add version subcommand

- src/hevm/stack.yaml
I would have updated to build with GHC 8.6, but that has problems with quickcheck's `Gen` not having a `MonadFail` instance
> Fix stack.yaml to build with GHC 8.4

- src/hevm/CHANGELOG.md
- src/hevm/default.nix
- src/hevm/hevm.cabal
- src/hevm/src/EVM/UnitTest.hs
this was an old, unnoticed bug in the unit-test runner, which was
brought to light when correct EIP684 collision semantics were recently
introduced. The nonce was being incorrectly reset to that of the
ethrun account, to adjust for it being potentially incremented during
the execution of the test contract's constructor, if that constructor
itself contains contract creations. However, since the creation
happens on behalf of the test contract, and not the ethrun address,
the nonce should be left as is, since replaceCode will propagate the
correct nonce.
Presumably this mistake was made because prior to commit
070cc9e39f23e1053da2c378d1d551d7f579be67, the nonce didn't get
propagated after a creation at all, so this line was introduced in a
flawed attempt to propagate it.
Any dapp tests which …
> hevm: UnitTest.hs: fix nonce initialisation bug (fixes #222)

- default.nix
- haskell.nix
- overlay.nix
- src/hevm/src/EVM.hs
- src/hevm/src/EVM/ABI.hs
- src/hevm/src/EVM/TTY.hs
- src/hevm/src/EVM/UnitTest.hs
This means we're using `release-19.03` at commit [`f1707d8875276cfa110139435a7e8998b4c2a4fd`](https://github.com/NixOS/nixpkgs/tree/f1707d8875276cfa110139435a7e8998b4c2a4fd) when pushing to cachix.
> Use release-19.03 as base

- nix/solc-updates.md
- nix/solc-versions.nix
Instead of adding versions for all platforms to `x86_64-darwin`, they can now be added to `common`.
> nix: clean up solc-versions.nix

- overlay.nix
- src/ethsign/default.nix
Now that the backported fixes have been upstreamed, there's no reason to keep pinning a version of geth.
This means we'll use the latest version in the pinned nixpkgs, which currently is 1.8.27.
> Use upstream geth

- nix/solc-versions.nix
It wasn't really common, since we had to remove elements from it for
macOS.
> nix: rename common attribute

- nix/solc-versions.nix
Using it fails with:
dyld: Library not loaded: /usr/lib/system/libsystem_network.dylib
Referenced from: /nix/store/xn55wd7nimdi085kji54mrrqqnqvcasz-Libsystem-osx-10.11.6/lib/libSystem.B.dylib
Reason: image not found
> solc: disable 0.4.24 on macOS

- src/dapp/CHANGELOG.md
- src/dapp/default.nix
- src/dapp/libexec/dapp/dapp
- src/dapp/libexec/dapp/dapp---version
- src/dapp/libexec/dapp/dapp-build
- src/dapp/libexec/dapp/dapp-debug
- src/dapp/libexec/dapp/dapp-test-hevm
- src/dapp/libexec/dapp/dapp-verify-contract
N.B. breaking change as .abi .bin and .bin-runtime artefacts are no longer generated.
Pass all of the source files to solc at once for much faster compilation. Previously we iterated through each file, which isn't necessary with the solc json output.
A positive side effect is no more test duplication in `dapp test`, which can occur with more complex projects (see e.g. https://github.com/makerdao/dss).
TODO:
> dapp: faster builds with single solc pass

- .travis.yml
- release.nix
- src/hevm/README.md
- src/hevm/ethjet/ethjet.c
- src/hevm/hevm-cli/hevm-cli.hs
- src/hevm/hevm.cabal
- src/hevm/run-blockchain-tests
- src/hevm/run-consensus-tests
- src/hevm/src/EVM.hs
- src/hevm/src/EVM/Concrete.hs
- src/hevm/src/EVM/Exec.hs
- src/hevm/src/EVM/FeeSchedule.hs
- src/hevm/src/EVM/Format.hs
- src/hevm/src/EVM/TTY.hs
- src/hevm/src/EVM/UnitTest.hs
- src/hevm/src/EVM/VMTest.hs
`call` has different write semantics to other operations, which generally pad with zeros up to any excess of size + offset over the data length. With `call`, `writeMemory`was erroneously truncating memory in the case of calls where the bytes to write were shorter than the memory size given. We fix this with a special write method for `call`.
A number of other memory writing issues were fixed:
- correct zero padding of non-call memory operations
- `returndatacopy` is meant to fail if reading from beyond what has been written.
- memory offset calculations are not modulo-256 in some cases
Lastly, test failures due solely to incorrect nonce or storage were separated and counted.
Previously:
```
passed: 5868
bad-balance: 3948
bad-nonce: 0
bad-storage: 0
failed: 245
skipped: 1923
```
Now (up to …
> hevm gst compliance

- src/ethsign/CHANGELOG
- src/ethsign/default.nix
- src/ethsign/ethsign.go
This command reads a hexadecimal private key and a desired passphrase
from stdin and saves a corresponding keyfile into the keystore using
Geth's standard options and file name scheme.
> ethsign: add import command

- release.nix
- src/hevm/src/EVM/Solidity.hs
This version just iterates over the two known bzzr prefixes, and correctly displays source maps for both new and old  `solc` versions, unlike #261. See commit message for details.
> hevm: Solidity.hs: strip using old and new bzzr prefixes

- src/hevm/hevm-cli/hevm-cli.hs
- src/hevm/src/EVM.hs
- src/hevm/src/EVM/Emacs.hs
- src/hevm/src/EVM/Stepper.hs
- src/hevm/src/EVM/TTY.hs
- src/hevm/src/EVM/Types.hs
- src/hevm/src/EVM/UnitTest.hs
A minimal fix for #257 where remote contracts are now correctly
fetched when running with the --rpc flag. Attempts to fetch
non-existant contracts will result in a VMFailure.
The fix is somewhat unsatisfactory because the tty interpreter
is not suited to gracefully handling operational failures without a
more extensive refactor of the stepper and other interpreters.
In the meantime rpc fetch is functional, with more robust and
informative error handling to follow.
> hevm: handle rpc fetch in tty - fixes #257

- src/hevm/src/EVM/UnitTest.hs
resolves #268 
Note that the [other configurables](https://github.com/dapphub/dapptools/blob/fix-test-init/src/hevm/src/EVM/UnitTest.hs#L576) like `DAPP_TEST_CALLER` and `DAPP_TEST_COINBASE` etc. weren't affected by this problem since they aren't part of the `state` and didn't get reset by `resetState`.
> hevm: fix msg.sender in test initialisation

- src/hevm/src/EVM/ABI.hs
- src/hevm/src/EVM/Format.hs
- src/hevm/src/EVM/Solidity.hs
- src/hevm/src/EVM/StorageLayout.hs
I am porting over the code used to support ABIv2 from [echidna](https://github.com/crytic/echidna/blob/master/lib/Echidna/ABIv2.hs). If possible, I would like some guidance on how to better write `readJSON` without passing around an extra `Maybe` parameter in its subroutines.
> Support ABIv2 in HEVM

- src/hevm/src/EVM/ABI.hs
This fixes a mistake I made earlier in the calculation of the size of dynamic tuples.
> Fix dynamic tuples

- src/dapp/libexec/dapp/dapp-create
- src/dapp/libexec/dapp/dapp-verify-contract
Supercedes #284
Co-authored-by: Brian McMichael <brian@brianmcmichael.com>
Co-authored-by: Christopher Mooney <chris@dod.net>
> fix dapp verify-contract

- src/hevm/stack.yaml
This small PR adds a missing dependency to build hevm using stack.
> Missing dependency in stack.yaml to build hevm

- src/dapp/libexec/dapp/dapp-address
- src/dapp/libexec/dapp/dapp-create
On dapp create, checksum and return the contract address.
Checksummed addressed are increasingly required by consuming services, and in the way that our scripts are using the dapp output it probably makes sense to put this here prior to handing it back to the user.
> Return the checksummed address after contract creation

- release.nix
- src/hevm/CHANGELOG.md
- src/hevm/src/EVM/Concrete.hs
- src/hevm/src/EVM/RLP.hs
- src/hevm/src/EVM/Transaction.hs
- src/hevm/src/EVM/VMTest.hs
Unfortunately, I introduced a bug in https://github.com/dapphub/dapptools/commit/f1b9b3485fa297a8ad5cd99c38e5ac6194970d11, wherein the rlp encoding of transactions wrapped some fields twice. I.e. a transaction:
```
(Transaction {txData = "", txGasLimit = 0x61a80, txGasPrice = 0x1, txNonce = 0x0, txR = 0xe94818d1f3b0c69eb37720145a5ead7fbf6f8d80139dd53953b4a782301050a3, txS = 0x1fcf46908c01576715411be0857e30027d6be3250a3653f049b3ff8d74d2540c, txToAddr = Just 0x95e7baea6a6c7c4c2dfeb977efac326af552d87, txV = 0x1c, txValue = 0x186a0})
```
was encoded as:
```
[0x80,0x01,0x83061a80,0x94095e7baea6a6c7c4c2dfeb977efac326af552d87,0x830186a0,0x80]
```
instead of:
```
[0x,0x01,0x061a80,0x095e7baea6a6c7c4c2dfeb977efac326af552d87,0x0186a0,0x]
```
This error caused blockchain-tests to not be able to …
> Vmtestsfix

- nix/solc-updates.md
- nix/solc-versions.nix
- overlay.nix
- src/dapp/CHANGELOG.md
- src/dapp/default.nix
- src/dapp/libexec/dapp/dapp---version
* Bumps solc to 0.5.15
* Disable the building of shared libs in Linux, which was difficult to maintain cause it required a patch that had to be kept in sync with upstream, for very little gain.
* bumps dapp to 0.26.0
when this is merged, create a `dapp/0.26.0` tag.
> solc 0.5.15

- .travis.yml
Avoids evaluating the whole package set, increasing performance.
This also, incidentally, solves a build failure we were having where the
version of nix used didn't have the `fromTOML` builtin used in a
recently introduced package.
Closes #322.
> travis: use -A argument for nix-env

- src/hevm/src/EVM/Solidity.hs
Just a little thing I noticed while investigating the embedded metadata hash. Solidity embeds `bzzr1` as part of the metadata identifier since solc 0.5.11 ([ref](https://github.com/ethereum/solidity/blob/385e1bf70a0389009af0da2f2f6054cd5b246619/Changelog.md#0511-2019-08-12))
Not sure what to test here, I ran: `nix build -f release.nix dapphub.linux.stable` and everything passes, but I guess there's something more I need to do?
> hevm: metadata: search for bzzr1 as well as bzzr0

- src/dapp/CHANGELOG.md
- src/dapp/libexec/dapp/dapp---hevm-opts
- src/dapp/libexec/dapp/dapp-test
- src/hevm/CHANGELOG.md
- src/hevm/hevm-cli/hevm-cli.hs
- src/hevm/src/EVM/ABI.hs
- src/hevm/src/EVM/Dapp.hs
- src/hevm/src/EVM/Dev.hs
- src/hevm/src/EVM/Emacs.hs
- src/hevm/src/EVM/TTY.hs
- src/hevm/src/EVM/Types.hs
- src/hevm/src/EVM/UnitTest.hs
Adds support for property based testing using `dapp`. By default, any test function which takes more than 0 arguments is interpreted as a property test, and it's arguments are randomly generated. 
The number of tests that are run can be modified with the `--fuzz-runs` flag, and defaults to `100`.
> Property based testing for dapps

- release.nix
- src/hevm/CHANGELOG.md
- src/hevm/default.nix
- src/hevm/ethjet/blake2.cc
- src/hevm/ethjet/blake2.h
- src/hevm/ethjet/ethjet.c
- src/hevm/ethjet/ethjet.h
- src/hevm/hevm-cli/hevm-cli.hs
- src/hevm/hevm.cabal
- src/hevm/run-blockchain-tests
- src/hevm/src/EVM.hs
- src/hevm/src/EVM/Emacs.hs
- src/hevm/src/EVM/Exec.hs
- src/hevm/src/EVM/FeeSchedule.hs
- src/hevm/src/EVM/Fetch.hs
- src/hevm/src/EVM/Op.hs
- src/hevm/src/EVM/TTY.hs
- src/hevm/src/EVM/UnitTest.hs
- src/hevm/src/EVM/VMTest.hs
Superseedes https://github.com/dapphub/dapptools/pull/304.
Still missing:
`CHAINID` should read from `--rpc` if one is passed
> Hevm istanbul

- .travis.yml
Instead of using any nixpkgs, we use the one this repo pins anyway. Currently, this means using [cachix 0.2.0](https://github.com/NixOS/nixpkgs/blob/f1707d8875276cfa110139435a7e8998b4c2a4fd/pkgs/development/tools/cachix/cachix.nix).
For some reason that has to do with issues with Cachix, this seems to be the only way to currently get pushes to work.
We can revisit this (e.g. by using [latest cachix](https://github.com/dapphub/dapptools/pull/331)) after [this migration](https://twitter.com/cachix_org/status/1222045505842073601) has completed.
Closes #331.
> travis: use cachix from pinned nixpkgs

- src/hevm/default.nix
- src/hevm/hevm.cabal
- src/hevm/src/EVM/Solidity.hs
This introduces the fix suggested in #333. `solc-0.6.2` also uses `ipfs` instead of `bzzr` so this works a bit better.
> fix `stripBytecodeMetadata`

- src/dapp/libexec/dapp/dapp-verify-contract
Etherscan API key is mandatory for all calls as of 2/15/2020. This adds the key to the checkverifystatus call.
> Add Etherscan API key to checkverifystatus

- src/seth/libexec/seth/seth---calldata-decode
I would use this to debug tx made by someone else with complex inputs, especially where the contract is not verified on etherscan (but I knew the signature, or got it from 4byte.directory for example).
Simple example:
```sh
foodata=$(seth calldata 'foo(uint256)' 444)
seth --calldata-decode 'foo(uint256)' "$foodata"  # 444
```
Practical example ([this failing tx](https://etherscan.io/tx/0x3fe4ccad0cc8f25a2ea5e915c0d80c017c5107b5cc142c7ab71c3a6caa7d233e)):
```sh
txinput=$(seth tx 0x3fe4ccad0cc8f25a2ea5e915c0d80c017c5107b5cc142c7ab71c3a6caa7d233e | awk '$1 == "input" {print $2}')
seth --calldata-decode \
'callOnExchange(uint,string,address[8],uint[8],bytes[4],bytes32,bytes)' "$txinput"
5
takeOrder(address,address[8],uint256[8],bytes[4],bytes32,bytes) …
```
> seth: add --calldata-decode

- src/hevm/src/EVM.hs
- src/hevm/src/EVM/Concrete.hs
- src/hevm/src/EVM/Types.hs
Not sure what the reasoning behind this memory bound was in the first place, but it causes hevm to have incorrect behaviour. Here's an example execution where `hevm` behaves differently to geth:
```
hevm exec --code 600063ffffffff52 --gas 351847752663100
OutOfGas 0x14000f0500033 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
```
```
evm --code 600063ffffffff52 --gas 351847752663100 --prestate customgenesis.json  --debug --nomemory run
0x
```
where `customgenesis.json` makes sure that the geth evm operates according to the Petersburg fork:
```
{
"alloc": {
},
"nonce": "0x000000000000002a",
"difficulty": "0x020000",
"mixhash": "0x0000000000000000000000000000000000000000000000000000000000000000",
"coinbase": "0x0000000000000000000000000000000000000000",
"timestamp": …
```
> hevm: remove (arbitrary?) memory bound

- nix/solc-versions.nix
- src/dapp/CHANGELOG.md
- src/hevm/src/EVM/Solidity.hs
draft pr for visibility,
Non-exhaustive list of things that need fixing in order to support `0.6.0` are:
-  Upgrade ds-test to follow the breaking changes convensions
-  Fix `Solidity.hs` to accomodate the new srcmap format
> Solc 0.6.0

- src/dapp/CHANGELOG.md
- src/dapp/libexec/dapp/dapp-create
Uses dapp.sol.json data for dapp create, without needing `--extract`
If there are multiple contracts with the same name (on different files) it fails. I believe this is the right thing to do, but wondering how to fix so that it's backwards compatible
```
$ dapp create MyContract
dapp-create: error: MyContract found in multiple files
src/MyContract.sol:MyContract
src/MyContract2.sol:MyContract
```
> dapp create without need of --extract

- .gitmodules
- overlay.nix
Recent updates to `seth` have broken much of the functionality in mcd-cli.
Current plan is to repair the functionality and build out `mcd-cli` as a distinct nix package so that we can better manage the dapptools version under the hood.
Since many of the features in the current distribution do not work with the current iteration of dapptools, we should remove it from the distribution to not encourage it's use.
> Remove mcd-cli

- src/hevm/src/EVM.hs
Current semantics does the opposite of what we want for precompiles – it causes a static mode violation iff the callvalue is zero.
Example bytecode for which hevm reverts and evm (geth) succeeds:
```
hevm exec --gas 0xffffff --code 0x600080541515601d576001815580818283305afa15601b578081fd5b005b80818283600160025af15050
evm --code 0x600080541515601d576001815580818283305afa15601b578081fd5b005b80818283600160025af15050 --gas 0xffffff --debug run
```
With this patch, `hevm exec` still fails because of an issue related to #273 (although the faulty semantics are still apparent in dapp tests), but in combination with #353 the behaviour of hevm exec matches that of geths
> hevm: fix STATICCALL for precompiles

- src/hevm/src/EVM.hs
so that contracts with `InitCode` may be ran normally without changing it to `RuntimeCode`
before, we initialized a contract was by
1. creating a contract with `RuntimeCode constructorCode`
2. exec'ing the constructor
3. replacing the contract with `InitCode ""`
4. call `replaceCode` on the target contract with the constructor result
this change lets us change 1 to `InitCode constructorCode` and omitting step 3.
> fix loadContract

- src/seth/libexec/seth/seth-calldata
fixes the notorious `seth calldata f(bool) false` issue @lucasvo
> seth calldata hack

- .travis.yml
- src/seth/Makefile
- src/seth/default.nix
- src/seth/libexec/seth/seth
puts the shellcheck check in seth (it's already in dapp) instead of in the travis file to solve our current ci problems
> Shellcheck

- default.nix
- src/dapp/Makefile
- src/ethsign/ethsign.go
- src/hevm/src/EVM/TTY.hs
Wholesale copy of default.nix and src/ethsign from the symbolic branch. 
Installed with following commands from a fresh clone after replacing default.nix and src/ethsign: 
```
git submodule init
git submodule update --recursive 
nix-env -i ethsign -f . 
```
> backporting fix to ethsign from symbolic

- haskell.nix
- nix/cvc4.nix
- nix/minisat-fenv.patch
- overlay.nix
factored out from #353, as it keeps timing out. Could also be useful on its own if someone is curious to try cvc4 out. It's pretty good on large bitvectors. Not suitable for nixpkgs upstream as it is a nightly version
> add cvc4 derivation and custom sbv_8_4

- src/dapp/libexec/dapp/dapp---testnet-launch
We need to make sure that the `rpc-url` is not taken from `.sethrc`.
> Force `seth` to use local `rpc-url`

- src/seth/default.nix
Currently `seth-calldata` is broken because of missing `jq`:
```
$ seth calldata "foo()"
/nix/store/ws5xsfv3p64000r0pjcv1fhkp5p7jagw-seth-0.9.0/libexec/seth/seth-calldata: line 14: jq: command not found
```
There is also some weird mergin conflict artifact in the dependencies, fixed here.
> src/seth/default.nix: add jq dependency to path, fix merge artifact

- nix/build-dapp-package.nix
We do `// args` at the end anyway.
> nix/build-dapp-package.nix: rm useless conditional

- src/hevm/CHANGELOG.md
- src/hevm/hevm-cli/hevm-cli.hs
- src/hevm/src/EVM.hs
- src/hevm/src/EVM/Dev.hs
- src/hevm/src/EVM/VMTest.hs
This makes `hevm exec` (and other commands) finalize transactions, which ensures that bytecode is replaced at creations, coinbase is paid and so on. 
`VMTest` cli endpoint is removed. I do not believe they have been run in quite some time, and what's being tested in VMTests is a proper subset of what's being done in `Blockchaintests` anyway.
> hevm: Remove `ExecMode`, always execute as blockchaintest

- overlay.nix
- src/dapp-tests/src/constantinople.sol
- src/dapp/CHANGELOG.md
- src/dapp/default.nix
- src/dapp/libexec/dapp/dapp---version
- src/hevm/src/EVM/Solidity.hs
Updates default solc to 0.6.7.
Actually, I want this to see if stuff like [this](https://github.com/dapphub/dapp-tools/runs/849891626?check_suite_focus=true) is a fluke, due to missing caches.
> dapp: 0.28.0

- .github/workflows/build.yml
Not necessary anymore, image size has been increased to 30GB.
> .github/workflows/build.yml: stop removing /opt

- nix/solc-versions.nix
Adding old version of solc not present in nixpkgs, as it is used by USDT.
> add solc 0.4.18

- src/seth/default.nix
- src/seth/libexec/seth/seth---nix-run
Turns out `seth` also depends on `DAPPTOOLS`....
> seth: set DAPPTOOLS in default.nix

- src/dapp/libexec/dapp/dapp-verify-contract
I am a noob at bash, so maybe there is a superior way to do this
the problem appeared to be that the argument being passed to `seth calldata` was in fact an empty string, or something along those lines, so checking for the existence of the variable `$4` and opting out of that branch if it is absent allows the script to run as planned
> verify-contract working when constrcutor args are absent

- src/hevm/CHANGELOG.md
- src/hevm/hevm-cli/hevm-cli.hs
- src/seth/libexec/seth/seth
- src/seth/libexec/seth/seth-call
- src/seth/libexec/seth/seth-run-tx
Adds a --trace flag to `hevm exec`, which will dump the execution trace.
Currently just the basic functionality, future prs will add more tracing features.
> hevm exec --trace

- .github/workflows/build.yml
- nix/hevm-tests/default.nix
- nix/hevm-tests/smt-checker.nix
- nix/hevm-tests/yul-equivalence.nix
- nix/hevm/tests.nix
- overlay.nix
- release.nix
This PR integrates two parts of the solc test suite and uses them to verify `hevm symbolic`:
1. the yul optimzer tests: a corpus of ~400 pairs of yul programs that have been written to be equivalant. Used to test `hevm equivalence`
2. the SMTCheker tests: a corpus of ~450 solidity contracts containing assertions, and annotations on whether or not those assertions should be violated. Used to test `hevm symbolic`
Not every test was useful in our context, but accounting for skipped tests, this gives us 474 new test cases.
The yul equivlance tests are run with both `cvc4` and `z3`, but the smt checker tests can only be run in  a reasonable time using `cvc4`. Interstingly `z3` is slightly faster on the equivalance tests (~30s for z3 and ~40s for cvc4 on my machine).
During the course of …
> Integrate solc test suite for hevm-symbolic

- .github/workflows/build.yml
Sorry I broke the CI :cry: I think this should fix it....
> ci: fix typo in hevm-tests invocation

- nix/hevm-tests/smt-checker.nix
- src/hevm/CHANGELOG.md
- src/hevm/src/EVM.hs
- src/hevm/src/EVM/Fetch.hs
- src/hevm/src/EVM/SymExec.hs
- src/hevm/src/EVM/TTY.hs
- src/hevm/test/test.hs
Fixes #456. I previously failed to add the knowledge gained from queries returning `Known`, thinking that if this only happens when there is only one alternative, in which case we are not really adding any new information. But `Known` can also be the result of a cached choice, so the newly gained knowledge should be stored.
> hevm: add knowledge to path conditions when query is Known

- src/dapp-tests/integration/tests.sh
Getting intermittent CI failures due to timeouts for this test (e.g. https://github.com/dapphub/dapptools/runs/974387432?check_suite_focus=true).
> dapp-tests: hevm symbolic: bump smttimeout for factorization

- src/hevm/hevm-cli/hevm-cli.hs
- src/hevm/hie.yaml
Some small changes that make `hevm` play nice with the haskell language server
- adds a `Module main where` declaration to `hevm-cli.hs`
- adds an `hie.yaml` file
> hevm: support hls

- src/hevm/src/EVM/ABI.hs
- fix underflow for values close to the bound
- squash compiler warning about inferred type for `mn`
> hevm: abi: fix large values in integral generator

- src/seth/README.md
* Added instructions on how to run on `Infura kovan testnet`
* This make sure the user is not confused and also set export `SETH_CHAIN=kovan` which does not work otherwise
> Added instructions on how to run on infura kovan testnet

- src/seth/README.md
- src/seth/libexec/seth/seth-chain-id
- src/seth/libexec/seth/seth-mktx
Network id can be helpful in scripts and the rpc command is not intuitive. 
* Added a seth command to return the network id
* Updated docs
* Update reference in mktx to use the alias
> Add chain-id function for returning the network id

- src/hevm/src/EVM/SymExec.hs
The current symbolic execution strategy always consults the solver on which branches of a JUMPI are possible. These intermediate queries lets us explore all possible behaviours, and then finally construct a query which checks each possible endstate against the postcondition (usually given by `assert`s).
Some experiments indicate that these intermediate branching queries are quite expensive.
This PR changes this execution strategy so that whenever we reach a branching point we have not seen before, we explore both branches without consulting SMT. This means that we can end up exploring more states than are possible, but since our final query always checks the pathconditions for consistency, this is safe and the extra paths will be pruned anyway.
The numbers for the `hevm-tests` suite look …
> Pessimistically explore both branches on new SMT queries

- src/seth/libexec/seth/seth-bundle-source
- src/seth/libexec/seth/seth-code
- src/seth/libexec/seth/seth-run-tx
- src/seth/libexec/seth/seth-source
Supersedes #432. Although #432 is still relevant, its kind of a big change and not something I'd like to push through right now. Instead, this PR does some easy fixes to ensure `seth debug` doesn't produce ridiculous results when calldata is short enough to be misinterpreted as a decimal string.
Also a small fix related to failing seth source queries
> Sethdebugfixes

- nix/solidity-package.nix
- nix/solidity-package.sh
- src/hevm/src/EVM/Flatten.hs
- Add `flatten` argument to `solidityPackage` to pass source through `hevm flatten`
- Fix to allow non-`solidity` `pragmas` being passed through `hevm flatten`
- Rename top scoped contracts and structs so not to cause naming conflicts on flatten
> Nix flatten solidity source

- src/dapp/libexec/dapp/dapp-test
Also don't think the `cd $DAPP_ROOT` are necessary, but will address those separately. @lucasvo @MrChico
> hotfix for 3f31ca3

- src/dapp/libexec/dapp/dapp---make-cache
- src/hevm/CHANGELOG.md
- src/hevm/README.md
- src/hevm/hevm-cli/hevm-cli.hs
- src/hevm/src/EVM.hs
- src/hevm/src/EVM/Dev.hs
- src/hevm/src/EVM/Emacs.hs
- src/hevm/src/EVM/Fetch.hs
- src/hevm/src/EVM/UnitTest.hs
- src/hevm/src/EVM/VMTest.hs
Mainly a clean up of `VMTest.hs`, removing things related to the ethereum tests/[VMTest](https://github.com/ethereum/tests/tree/develop/VMTests) which we haven't run in quite a while, as well as simplifying things generally.
One of my concerns here is to try to use less special case logic when running the ethereum tests, so that we can increase confidence in the correctness of other endpoints.
I'm also adding the setupTx functionality to `UnitTest` so that gas is paid for appropriately, fixing #511. If the sending address cannot afford the initial gas deposit this yields a hard error.
This `setupTx` (and `initTx`) process which increments the origin nonce, pays for gas, and sets the relevant tx reversion state is not done for the `hevm exec` or `hevm symbolic` endpoints right now, but I …
> Simplify VMTest for a unified transaction initialization procedure

- haskell.nix
- src/seth/default.nix
- Fix for reported error: `/nix/store/gb73icd6lliyyn6f33l29bydjqklv01k-seth-0.8.2/libexec/seth/seth---field: line 3: grep: command not found`
- Also couldn't do `nix-build -A seth` because of a trailing slash in `https://github.com/LeventErkok/sbv/` causing `ERROR: Repository not found.`
> Fix seth missing grep

- default.nix
Because of excruciating download times for `nixpkgs` when using `fetchGit` on CIs where no cache/store is already populated.
> Use `fetchTarball` instead of `fetchGit` to get `nixpkgs`

- src/hevm/hevm.cabal
- src/hevm/src/EVM.hs
- src/hevm/src/EVM/Format.hs
- src/hevm/src/EVM/Solidity.hs
- src/hevm/src/EVM/VMTest.hs
- src/hevm/test/test.hs
as the cborg based detection could not account for constructor args,
resulting in no srcmaps for init methods with arguments.
Revert "fix stripBytecodeMetadata"
This reverts commit 78508c6a8db2d6d3e8e09437dbe122bb5e6b2e7e.
> Fall back to old method for detecting bytecode metadata

- src/hevm/hevm-cli/hevm-cli.hs
- src/hevm/src/EVM.hs
- src/hevm/src/EVM/Fetch.hs
- src/hevm/src/EVM/Format.hs
- src/hevm/src/EVM/SymExec.hs
- src/hevm/src/EVM/UnitTest.hs
Passing the storagemodel in oracle can lead to inconsistencies. This solves #541.
> get storagemodel from PleaseFetchAccount, not in oracle

- .github/workflows/build.yml
- src/dapp-tests/Makefile
- src/dapp-tests/integration/diff-fuzz.py
- src/dapp-tests/integration/tests.sh
- src/dapp-tests/shell.nix
- src/hevm/hevm-cli/hevm-cli.hs
- src/hevm/src/EVM.hs
- src/hevm/src/EVM/Concrete.hs
- src/hevm/src/EVM/Dapp.hs
- src/hevm/src/EVM/Debug.hs
- src/hevm/src/EVM/Dev.hs
- src/hevm/src/EVM/Transaction.hs
- src/hevm/src/EVM/Types.hs
superseedes #546.
This PR introduces the json tracing functionality discussed in #288, and sets up some basic infrastructure for differentially testing hevm against geth. In the process I found a couple of issues:
- If a PUSH opcode is given too short data, geth pads it to the appropriate length, while hevm just takes the data it is given, effectively leftpadding the bytestring. I don't believe this can ever actually make a meaningful difference, since the only setting in which this can occur is if the PUSH instruction is the final instruction of a contract, so the value will be ignored on the stack anyway. Regardless, I have adjusted hevm to also rightpad the data.
- hevm can panic in TTY mode if it tries to navigate beyond the final opcode (try for example `hevm exec --code …
> Gethcompliance

- src/dapp/CHANGELOG.md
- src/dapp/README.md
- src/dapp/libexec/dapp/dapp---hevm-opts
- src/hevm/CHANGELOG.md
- src/hevm/hevm-cli/hevm-cli.hs
- src/hevm/src/EVM/Dapp.hs
- src/hevm/src/EVM/Dev.hs
- src/hevm/src/EVM/Emacs.hs
- src/hevm/src/EVM/Fetch.hs
- src/hevm/src/EVM/Format.hs
- src/hevm/src/EVM/Transaction.hs
- src/hevm/src/EVM/UnitTest.hs
Extends the dapp test --match argument with contract name and file path, retaining the current behaviour.
> hevm unittest improvements

- src/hevm/CHANGELOG.md
- src/hevm/README.md
- src/hevm/src/EVM/TTY.hs
Adds the ability to step through the callstack (actually the trace tree to be precise) by using the up and down arrow keys in debug mode.
As the trace pane grows, we now follow it so that new entries are always visible. This can look a little wonky when backstepping (sometimes we only see the last entry, hiding previous ones even though there's space), but I think this is good enough for now.
Also fixes an issue where it was possible to step past the end of execution (try pressing `e` and then `N` on master right now).
> hevm debug: step through the callstack using up and down arrows

- src/hevm/src/EVM/UnitTest.hs
We were using a hardcoded oracle here, and it was breaking when trying to execute symbolic tests against rpc state.
This fix ensures that the oracle used for the symbolic tests is constructed with the required rpc parameters if they are provided at the command line.
Thanks @MrChico for the help :sparkling_heart:
> UnitTest: fix symbolic rpc tests

- src/hevm/src/EVM.hs
- src/hevm/src/EVM/UnitTest.hs
This commit tidies the error messages shown for counter examples in symbolic tests.
- Failures due to an SMT timeout are now shown in the result field instead of in the calldata field
- Failures due to a DSTest assertion violation are now shown as such instead of the "32 symbolic bytes shown previously"
Note: the current text in the result field for DSTest assertion violations is perhaps a little too similar to that for an EVM assertion violation, I'm not sure what a better choice would be?
SMT Timeout:
```
Counter Example:
result:   Return: 32 symbolic bytes
calldata: SMT Timeout
```
DSTest Assertion Violation:
```
Counter Example:
result:   Return: 32 symbolic bytes
calldata: prove_fail()
```
SMT timeout:
```
Counter Example:
result:   Failed: SMTTimeout
calldata: unknown
```
DSTest …
> UnitTest: tidy result in counter examples

- nix/hevm-tests/smt-checker.nix
- src/dapp/libexec/dapp/dapp-test
- src/hevm/CHANGELOG.md
- src/hevm/hevm-cli/hevm-cli.hs
- src/hevm/hevm.cabal
- bumps the default smt timeout to 30s from 20s
- keeps the old timeout in place for the smt-checker tests
- adds a new hevm release (will tag once the PR is approved)
> Bump smttimeout / release hevm 0.43.2

- src/dapp/libexec/dapp/dapp
- src/dapp/libexec/dapp/dapp-build
- src/seth/libexec/seth/seth
- Ensures `dapp mk-standard-json` uses `dapp remappings` correctly.
- Warns if deprecated SOLC_FLAGS is used
- Ensure SETH_CHAIN doesn't influence whether SETH_LOGS_API uses etherscan or rpc. @gakonst
> warn about SOLC_FLAGS

- src/dapp/libexec/dapp/dapp-test
The current check for libraries is currently a heuristic one, and can fail, resulting in unescessary library deployments when running dapp test.
This is reasonably time consuming, and so until a more accurate library check is developed (perhaps as part of hevm itself), we allow users to skip library linking by setting `DAPP_LINK_TEST_LIBRARIES=0` before calling `dapp test`.
> dapp: allow users to skip library linking for dapp-test

- nix/build-dapp-package.nix
- src/dapp-tests/default.nix
- src/dapp-tests/pass/cheatCodes.sol
- src/hevm/src/EVM.hs
- src/hevm/src/EVM/ABI.hs
- src/hevm/src/EVM/Types.hs
- src/hevm/test/test.hs
hevm cheat codes can now accept symbolic arguments, allowing symbolic jumps in time, or `store` / `load` for symbolic values. `roll` will still fail with `UnexpectedSymbolicArg` as the block number is currently not symbolic at the VM level.
> hevm: allow symbolic arguments to cheatcodes

- nix/solc-versions.nix
- src/dapp/CHANGELOG.md
Support for solc 0.7.4 (linux and mac) and 0.8.1 for linux in the old school solc-versions
> Solcversions

- src/dapp-tests/pass/dsProvePass.sol
- src/hevm/CHANGELOG.md
- src/hevm/hevm-cli/hevm-cli.hs
- src/hevm/src/EVM.hs
- src/hevm/src/EVM/Debug.hs
- src/hevm/src/EVM/Dev.hs
- src/hevm/src/EVM/Emacs.hs
- src/hevm/src/EVM/Exec.hs
- src/hevm/src/EVM/Facts.hs
- src/hevm/src/EVM/Fetch.hs
- src/hevm/src/EVM/Op.hs
- src/hevm/src/EVM/Solidity.hs
- src/hevm/src/EVM/SymExec.hs
- src/hevm/src/EVM/Symbolic.hs
- src/hevm/src/EVM/UnitTest.hs
- src/hevm/src/EVM/VMTest.hs
- src/hevm/test/test.hs
Allows for constructor arguments to be symbolic, as in [this example](https://github.com/dapphub/dapptools/blob/constructorArg/src/dapp-tests/pass/dsProvePass.sol#L38)
> Admit symbolic bytecode

- src/dapp/libexec/dapp/dapp-mk-standard-json
- src/hevm/CHANGELOG.md
- src/hevm/src/EVM.hs
- src/hevm/src/EVM/ABI.hs
- src/hevm/src/EVM/Dapp.hs
- src/hevm/src/EVM/Emacs.hs
- src/hevm/src/EVM/Solidity.hs
- src/hevm/src/EVM/TTY.hs
- src/hevm/src/EVM/Transaction.hs
- src/hevm/src/EVM/Types.hs
- src/hevm/src/EVM/UnitTest.hs
- src/seth/CHANGELOG.md
- src/seth/libexec/seth/seth-bundle-source
- src/seth/libexec/seth/seth-solc
This PR lets us have srcmaps for contracts with immutable variables. If the hash based identification of a contract fails, we look at all the known contracts with immutable vars and see if our current bytecode matches any of them if we overwrite possible mutability locations with zeros.
There's also a fix for `seth bundle-source` to write all relevant contracts to disk when getting dealing with std-json artifacts from etherscan (i.e. multiple srcs, not flattened).
> identify code modulo `immutable` and fix stdjson bundling from etherscan

- src/hevm/src/EVM/Solidity.hs
- src/seth/CHANGELOG.md
This field is called `storageLayout` in std json output...
> hevm: Solidity: fix key name for storage-layout when parsing stdjson

- .gitignore
- src/restless-git/src/Restless/Git.hs
restless-git was previously assuming that the default branch of a git repo was always `master`. This assumption does not always hold, so this PR makes it so that the `defaultRef` is instead read directly from the git config for the repo in question.
> restless-git: read default ref from git config

- nix/solc-static.nix
The static solc builds look up `z3` at runtime using `dlopen`, this PR wraps the binaries to make sure `LD_LIBRARY_PATH` is pointing to the right place.
> nix: add libz3.so.4.8 to LD_LIBARY_PATH for static solc binaries

- nix/solc-static.nix
Getting reports in chat that this is broken on osx, reverting for now....
This reverts commit 2139b124d6ffa458fef433b5c0bdeadd3b3d5a28.
> Revert "nix: add libz3.so.4.8 to LD_LIBARY_PATH for static solc binaries"

- nix/solc-static-versions.nix
- nix/solc-static.nix
Adds `solc-0.8.4` and uses our copy of z3 for linux builds only (since the approach here was broken on macos).
@MrChico @kjekac could one of you try running `nix-env -f https://github.com/dapphub/dapptools/archive/d194301f1c81ff8819c95823cebda68d771d283a.tar.gz -iA solc-static-versions.solc_0_8_4` before merge just to make sure I didn't mess anything up with the macos builds.
> Fixup solc linux

- src/dapp-tests/fail/invariantFail.sol
- src/dapp-tests/pass/invariants.sol
- src/hevm/src/EVM.hs
- src/hevm/src/EVM/Dapp.hs
- src/hevm/src/EVM/TTY.hs
- src/hevm/src/EVM/UnitTest.hs
Fixes (mostly) a performance regression in dapp debug introduced in #593 and introduces the ability to select which contracts to chose methods from during invariant testing. If a function `targetContracts()(address[])` is present in the current testing contract. See some examples in the testing files
> invariant testing fixes

- nix/solc-static-versions.nix
Adds solc 0.8.5/0.8.6 to `solc-static-versions.nix`
Generated using `./make-solc-static.sh`
> nix: add solc-0.8.5/0.8.6

- src/dapp/CHANGELOG.md
- src/dapp/README.md
- src/dapp/libexec/dapp/dapp
- src/dapp/libexec/dapp/dapp-test
Purges all mention of the broken `-vv` flag.
see: https://github.com/dapphub/dapptools/pull/657
> rm mentions of -vv (was broken)

- src/hevm/src/EVM/TTY.hs
whenever one tries to debug a fuzz test which features a type which doesn't have a corresponding symbolic version (i.e. `bytes` or other dynamically sized types), hevm currently fails as we try to generate a symbolic argument (which will be thrown away regardless). This quick fix ensures that we only create the symbolic argument if it is actually a symbolic test
> fix debug bug

- src/hevm/src/EVM/Solidity.hs
Fixes some issues with json parsing:
1. storage layout was being parsed as a string, when it is an object in the std-json output (and also in the combined json output post solc 0.8)
2. abis were being parsed as a string in the combined json output, but they are an object post solc 0.8
Note that this change currently breaks parsing of storage layout for combined-json output from solc < 0.8. I'm happy to make this work if we consider it important, but since it's a deprecated option, and I couldn't figure out a clean way to make it work after 20 minutes I just left it alone.
We could maybe also just consider removing the `combinedJSON` parsing code as part of this PR as well?
> Fix storage layout parsing

- src/dapp/README.md
1. Fix messed up markdown
2. Remove references to `solc-versions.nix` as it seems very outdated and unused(?)
3.  Fix links to `solc-static-versions.nix`
4. Explain how `DAPP_SOLC_VERSION` env var behaves wrt to `--use`
> dapp: README fixes

- src/hevm/src/EVM/Solidity.hs
- src/hevm/src/EVM/Symbolic.hs
- src/hevm/test/test.hs
`NOT` is bitwise negation, which is implemented in haskell with `complement` not `negate`. This was causing the soundness issue in: https://github.com/dapphub/dapptools/pull/698.
> hevm: Symbolic: correct semantics for Neg in whiffValue

- src/hevm/hevm.cabal
If we leave this on `0.47.0` then cabal always selects the hackage release instead of the version we provide via nix when I try to use hevm master in act. I don't know why that is the case, but bumping the hevm version and increasing the version bound in `act.cabal` finally meant that CI would pass here: https://github.com/ethereum/act/pull/116
> bump hevm version

- src/dapp-tests/pass/dsProvePass.sol
- src/hevm/test/test.hs
CI has been somewhat flakey since we switched back to z3 as a default. Removing one of the more expensive tests here in the hope that our CI jobs will stop getting killed due to OOM...
> hevm: rm expensive unit test

- README.md
- src/dapp/README.md
- src/ethsign/README.md
- src/seth/README.md
Originally made this PR was to write down how `ethsign import` can be used to generate a keystore file `seth` can ingest, but got a bit carried away and added some more env vars to the `dapp` table and cleaned up some grammar/spelling/casing 😅
> More README improvements

- src/dapp/libexec/dapp/dapp---use
- src/seth/libexec/seth/seth---use
i'm not sure if there's a reason we currently use `solc-versions` but trying this out because `solc-versions` is missing most of the modern solc builds that i depend on lol
> dapp/seth: use solc-static for --use

- src/dapp/CHANGELOG.md
- src/dapp/libexec/dapp/dapp-remappings
This downgrades the dreaded mismatched packages error to a warning, and removes the useless `index.sol` remappings from the `dapp remappings` output.
> Loosen remappings warning

- src/dapp/CHANGELOG.md
- src/dapp/default.nix
- src/dapp/libexec/dapp/dapp---use
- src/dapp/libexec/dapp/dapp-build
- src/ethsign/default.nix
- src/seth/default.nix
The solc binaries from `solc-static-versions` have the version as a suffix (e.g. `solc-0.8.6`), meaning that they needed a bit of massaging to use them in `dapp --use`.
Instead of just using the package definition directly, we instead create a tiny wrapper package that renames the version prefixed binary to `solc` on demand.
I also squashed the warnings about `stdenv.lib` as part of this pr.
> Fix dapp use

- src/hevm/CHANGELOG.md
- src/hevm/hevm.cabal
- src/hevm/src/EVM.hs
- src/hevm/src/EVM/Facts.hs
- src/hevm/src/EVM/Fetch.hs
- src/hevm/src/EVM/StorageLayout.hs
Not the optimization I set out to make, but this one is quite simple and still provides some marginal improvement.
Fetches account code, balance and nonce concurrently instead of sequentially. This provides around 30% speedup of a single account fetching. Against a larger example (`--match test_reward_wound_fully` of https://github.com/rainbreak/crop), the improvement is less pronounced (~1:52 to 1:50), but for the size of the diff it's maybe worth it still
> fetch contract code, nonce and balance asynchronously

- src/hevm/CHANGELOG.md
- src/hevm/README.md
- src/hevm/hevm-cli/hevm-cli.hs
- src/hevm/src/EVM.hs
- src/hevm/src/EVM/Dev.hs
- src/hevm/src/EVM/Emacs.hs
- src/hevm/src/EVM/Solidity.hs
- src/hevm/src/EVM/SymExec.hs
- src/hevm/src/EVM/TTY.hs
- src/hevm/src/EVM/UnitTest.hs
- src/hevm/test/test.hs
the result returned from `verify` did not distinguish between a succesful run and a run where the solver timed out on the postcondition query, meaning that users of `verify` would treat a timeout as a success, and resulted in e.g. act printing `Q.E.D` even if the query timed out.
> hevm: symexec: verify: differentiate timeouts and success

- src/hevm/hevm-cli/hevm-cli.hs
replaces the confusing symbols of `hevm --coverage` with pretty terminal colors
> hevm: Colored coverage output

- README.md
hevm README link currently points at dapp/README.md
_Utterly_ minor, but I was reading up on hevm to start tackling a first issue and got pretty confused
> Correct hevm README.md link

- src/dapp-tests/integration/tests.sh
- src/seth/README.md
- src/seth/libexec/seth/seth-lookup-address
- src/seth/libexec/seth/seth-namehash
- src/seth/libexec/seth/seth-resolve-name
Adds the following:
- `seth namehash <name>` to get the ENS namehash of a name
- `seth resolve-name <name>` to resolve an ENS name to an address
- `seth lookup-address <address>` to lookup the ENS name an address reverse resolves to
Also adds tests for the ENS methods which are required to run against a forked mainnet. These may break in the future if the resolution for those names changes. To simplify things, I hardcoded a mainnet RPC URL using the same community provided Infura endpoint that ethers uses, but I'm open to other suggestions here
ENS names are converted to lowercase before hashing, but note this is not the complete [normalization process](https://docs.ens.domains/contract-api-reference/name-processing#normalising-names), so users must ensure the ENS names they enter are …
> `seth`: add ENS support

- nix/solc-static-versions.nix
Adds solc 0.8.7 to `solc-static-versions.nix`, generated using `./make-solc-static.sh`
> Add support for solc 0.8.7

- .github/workflows/release.yml
This PR fixes the path of the `macOS-hevm.tar.gz` to correctly include it in the releases.
The Github action for the macOS `hevm` binary is currently not working.
```
// https://github.com/dapphub/dapptools/runs/3255462191
🤔 Pattern 'hevm-macOS.tar.gz' does not match any files.
```
Example pipeline: https://github.com/bernard-wagner/dapptools/actions/runs/1189824034
> ci: fixed macos artifact upload

- src/seth/CHANGELOG.md
- src/seth/libexec/seth/seth---send-params
- src/seth/libexec/seth/seth-estimate
Fixes #765 
When estimating gas, provide the `NO_GAS` flag to `seth --send-params` so that the `gas` field is not populated, and we can let the node do gas estimation for us.
> fix: do not set the `gas` field when estimating gas

- src/seth/CHANGELOG.md
- src/seth/README.md
- src/seth/libexec/seth/seth-send
Previously, if ETH_RPC_ACCOUNTS was set, seth-send would always use the node's
accounts as its signers. Now, even if it's set, it'll first check if the specified
ETH_FROM is in the keystore, and use it if so.
> feat: expand sign and send cases

- src/hevm/CHANGELOG.md
- src/hevm/src/EVM/Fetch.hs
- src/hevm/src/EVM/UnitTest.hs
The block gas limit and block basefee are now correctly set when running tests via rpc. 
@mds1 this should fix the issue you were seeing [here](https://github.com/dapphub/dapptools/pull/743#issuecomment-899481642).
Thanks @transmissions11 for spotting this! :pray:
> hevm: correctly set basefee and gas limit when running with --rpc

- src/ethsign/CHANGELOG
- src/ethsign/ethsign.go
Previously we would always require a keystore to be provided with `ethsign --import`, when that should not be required.
> fix: use default keystore when importing

- src/dapp/CHANGELOG.md
- src/dapp/README.md
- src/dapp/libexec/dapp/dapp---parse-deps
- src/dapp/libexec/dapp/dapp-install
As title, right now we cannot specify a rev/branch/tag when installing a version. 
We allow providing one after an "@". we clone the repo in a dir that preserves the version/tag so that we can know what version we've installed at a glance.
e.g. if you wanted to install an older version of OZ, you'd do `dapp install https://github.com/OpenZeppelin/openzeppelin-contracts@release-v3.3`
Example (`dapp upgrade` still works and updates to the latest master):
```
mkdir test-deps
cd test-deps
dapp init
dapp install rari-capital/solmate@92f9f3ff441d3e2e07b4c8764632659c2557467e
dapp upgrade
```
> feat: allow specifing version to `dapp install` url

- src/seth/CHANGELOG.md
- src/seth/libexec/seth/seth---to-wei
This will make `seth --to-wei` use `eth` as the default unit instead of `wei`. This makes more sense, given the helptext `convert an ETH amount into wei`
> use eth instead of wei as default for `seth --to-wei`

- src/seth/CHANGELOG.md
- src/seth/README.md
- src/seth/libexec/seth/seth
- src/seth/libexec/seth/seth-4byte
- src/seth/libexec/seth/seth-4byte-decode
- src/seth/libexec/seth/seth-4byte-event
- src/seth/libexec/seth/seth-abi-encode
- src/seth/libexec/seth/seth-index
- src/seth/libexec/seth/seth-sig
- src/seth/libexec/seth/seth-slot
Leaving this as a draft until I add docs to the README / review the existing comments.
Also looking for feebdack on the method names and syntaxes, e.g. `seth slot` feels a bit clunky to me, but I don't think there's a more concise way to generalize this
> seth: add function selector and calldata encoding/decoding helpers

- src/dapp/CHANGELOG.md
- src/dapp/libexec/dapp/dapp-remappings
Files from MacOS finder like .DS_Store and other junk can end up in the libs folder and mess up remappings, this should fix
> dapp: Ignore non-directories in dapp-remappings

- src/seth/CHANGELOG.md
- src/seth/libexec/seth/seth---to-wei
This reverts commit 8ab1a85fe6ffc6df23aef800c93c7cf429aa9a98. Changing `--to-wei` also changed the default values used in `seth send` and many other places, which could lead to way too much eth being transferred!
> Revert "use eth instead of wei as default for `seth --to-wei`"

- src/dapp-tests/pass/abstract.sol
- src/hevm/CHANGELOG.md
- src/hevm/src/EVM/Dapp.hs
Skips execution for unit test contracts with no code. Fixes #769.
> hevm: skip unit test contracts with no code

- src/dapp-tests/integration/tests.sh
- src/seth/CHANGELOG.md
- src/seth/libexec/seth/seth-send
Fixes an issue in #771, where if `ETH_RPC_ACCOUNTS` was set, and `ETH_FROM` was not a checksummed address, the signing request would be incorrectly forwarded to the rpc node, even if `ETH_FROM` was present in a local keystore.
The issue is fixed by using a case insensitive grep when checking if `ETH_FROM` is present in a local keystore.
> seth: non checksum addresses supported in ETH_FROM

- src/dapp-tests/integration/tests.sh
- src/seth/CHANGELOG.md
- src/seth/README.md
- src/seth/libexec/seth/seth---from-fix
- src/seth/libexec/seth/seth-4byte-decode
- Adds `--from-fix command`
- Add `--from-fix` and `--to-fix` methods to the docs
- Fix unrelated typo in `seth 4byte-decode`
This is a super simple method but let me know if you still want to add tests
> Add `--from-fix` command

- src/hevm/src/EVM/Op.hs
- Pretty printing for `0xfe` in debug view
- Print hex code instead of decimal value for other undefined opcodes
> clearer output for the invalid opcode

- src/dapp/CHANGELOG.md
- src/dapp/libexec/dapp/dapp-build
- strips '\\' chars from the output
- colors errors in red, and warnings in yellow
Fixes  #659
> dapp: build: strip escape chars and colorize output

- src/dapp/libexec/dapp/dapp-verify-contract
- src/seth/README.md
- src/seth/libexec/seth/seth
- src/seth/libexec/seth/seth-chain
- src/seth/libexec/seth/seth-etherscan-source
Add Polygon support for `seth chain`, `seth etherscan-source`, and `dapp verify-contract`. Please let me know how I should update the changelog as well as I am not too sure about that.
Also, it appears that for most chains, `seth etherscan-source` is broken. This is because most of the `ETHERSCAN_API_URL` set at the `seth` entrypoint has the /api portion included, but `seth etherscan-source` expects it to not be included. This is breaking my Polygon integration, as well as several others (I tested myself to confirm that it does not work for mainnet or kovan too but I beleive all but arbitrum are broken). Am I misunderstanding something here? I'd be happy to open a new PR to fix it.
> Add Polygon Support

- nix/solc-static-versions.nix
- src/hevm/CHANGELOG.md
Fixes #858 
Ran
```
$ ./nix/make-solc-static.sh
```
To generate the `solc-static-versions.nix` content, in order to support Solidity version 0.8.10.
> hevm/dapp: solc 0.8.10 support

- src/dapp/CHANGELOG.md
- src/dapp/default.nix
- src/dapp/libexec/dapp/dapp---version
- src/ethsign/CHANGELOG
- src/ethsign/default.nix
- src/hevm/CHANGELOG.md
- src/hevm/hevm.cabal
- src/seth/CHANGELOG.md
- src/seth/default.nix
- src/seth/libexec/seth/seth---version
> Release candidate

- .github/workflows/release.yml
https://github.com/dapphub/dapptools/commit/2fcfa9cce68a430226dc6dddbeb593925279104e updated the cachix version for the build workflow, but was not updated for the release workflow, attempting to unblock release
> cachixbump release.yml

- src/hevm/README.md
I wanted to make a small change to make the ffi documentation a little more noob friendly. HEVM throws an error if anything in stdout is not encoded properly. Let me know if you want me to change anything up!
> Small update to ffi function documentation

- ARCHITECTURE.md
change `./src/seth/libexec/dapp/dapp` -> `./src/dapp/libexec/dapp/dapp`
> Fix dapp script path typo in ARCHITECTURE.md 

- nix/solc-static-versions.nix
- src/hevm/CHANGELOG.md
Ran
```
$ ./nix/make-solc-static.sh
```
To generate the `solc-static-versions.nix` content, in order to support Solidity version 0.8.12.
> 🥄 Add support for solc 0.8.12

- src/seth/README.md
the ";" was resulting in
```
unknown modifier: ;
[{"anonymous":false,"inputs":[{"type":"uint256","name":"bar","indexed":false}],"name":"Foo","type":"event"}]
```
and without the ";" we now just get
```
[{"anonymous":false,"inputs":[{"type":"uint256","name":"bar","indexed":false}],"name":"Foo","type":"event"}]
```
> fixed typo

- nix/solc-static-versions.nix
- src/hevm/CHANGELOG.md
Add support for solc `0.8.13`. The content was generated using `$ ./nix/make-solc-static.sh`.
> Add support for solc 0.8.13

- nix/solc-static-versions.nix
- src/hevm/CHANGELOG.md
Add support for solc `0.8.14`. The content was generated using `$ ./nix/make-solc-static.sh`.
> 🖖 add solc 0.8.14 and keep dapptools up-to-date

- nix/solc-static-versions.nix
- src/hevm/CHANGELOG.md
Add support for solc `0.8.15`. The content was generated using `$ ./nix/make-solc-static.sh`.
Cc: @d-xo @cleanunicorn
> 🖖 add solc 0.8.15 and keep dapptools up-to-date

- src/hevm/CHANGELOG.md
- src/hevm/src/EVM/UnitTest.hs
Since https://github.com/dapphub/ds-test/pull/30 calls to `failed()` can
contain reverting branches due to the call into abi.decode().
This meant that using prove tests with the latest ds-test version would
always fail with a hard error.
This change updates the symbolic test stepper to correctly report
`bailed` as true for branches that reverted during the call to
`failed()`.
> hevm: fix prove tests for latest ds-test

- nix/solc-static-versions.nix
- src/hevm/CHANGELOG.md
Add support for solc `0.8.16` & `0.817`. The content was generated using `$ ./nix/make-solc-static.sh`.
Cc: @d-xo
> 🖖 add solc `0.8.16` & `0.8.17` and keep dapptools up-to-date

- nix/solc-static-versions.nix
- src/hevm/CHANGELOG.md
Add support for solc `0.8.18`. The content was generated using `$ ./nix/make-solc-static.sh`.
Cc: @d-xo
> ♻️  add solc `0.8.18` support

- nix/solc-static-versions.nix
- src/hevm/CHANGELOG.md
Add support for solc `0.8.19`. The content was generated using `$ ./nix/make-solc-static.sh`.
Cc: @d-xo
> ♻️ add solc `0.8.19` support

- .envrc
Used by [`nix-direnv`](https://github.com/nix-community/nix-direnv).
> envrc: init

- README.md
- flake.nix
- fixes the in-flake nix config: `extra-substituters-public-keys` -> `extra-trusted-public-keys`
- simplifies the creation of the `packages` attribute
-
> `flake`: fix caching config

- src/dapp-tests/integration/tests.sh
See https://github.com/dapphub/dapptools/pull/969 and https://github.com/dapphub/dapptools/pull/977#issuecomment-1444421022
> tests: integration: disable 4byte due to flakiness

- nix/solc-static-versions.nix
- src/hevm/CHANGELOG.md
Add support for solc `0.8.20`. The content was generated using `$ ./nix/make-solc-static.sh`.
Cc: @d-xo
> ♻ ️ Add support for Solidity version `0.8.20`
